### ISSUE TITLE
Error: Cannot parse response to an image.

### ISSUE THREAD

**Issue by BrendonGames** [ckosmic/ScoreSaberWidget#1]
The title is the error i’m receiving and I have no idea why it happens.

here’s a photo of the error:
![773F9EB2-E247-4FDC-9926-7C5A14A41283](https://user-images.githubusercontent.com/89480896/184353082-8105a67a-85de-4747-940e-714f82655962.jpeg)

I’ve been using this widget for a while and it suddenly stopped working.
I waited a few hours and reinstalled, but it still doesn’t work.

**Comment by ckosmic** [comment]
Looks like the ScoreSaber API or frontend changed :/ I'll look into it.

**Comment by qe201020335** [comment]
It is because ScoreSaber no longer serves the country flags pictures. It is using [twemoji](https://github.com/twitter/twemoji)'s image.
`https://scoresaber.com/imports/images/flags/ca.png` will return 404 instead of the flag for Canada.

Here is how ScoreSaber fetches the twimoji https://github.com/ScoreSaber/ScoreSaber-Frontend/blob/main/src/lib/components/image/country-image.svelte

**Comment by BrendonGames** [comment]
Although I’m not good enough to get the image, I have managed to rewrite the code a little to add the country as text:
![E4838FE1-D3F9-4446-80BF-92B25E7E4B9F](https://user-images.githubusercontent.com/89480896/184946022-52022a04-d666-4faa-a1fb-0bb821a22714.jpeg)

**Comment by BrendonGames** [comment]
Here's the scriptable file for plain text country:
[ScoreSaber.zip](https://github.com/ckosmic/ScoreSaberWidget/files/9353487/ScoreSaber.zip)

**Comment by qe201020335** [comment]
The flag image returned by twimoji is svg and I did some google found out Scriptable doesn't really have a good support for svg.

Here is the code I copied from the ScoreSaber frontend.
```js
const toTwemojiFlag = (input) =>
    `https://twemoji.maxcdn.com/v/13.1.0/svg/${input
        .toLowerCase()
        .match(/[a-z]/g)
        .map((i) => (i.codePointAt(0) + 127365).toString(16))
        .join('-')}.svg`;

const toEmojiFlag = (countryCode) => countryCode.toLowerCase().replace(/[a-z]/g, (i) => String.fromCodePoint((i.codePointAt(0) ?? 0) - 97 + 0x1f1e6));
```
`toTwemojiFlag` will return a url to the country flag svg which we can't use at the moment.
`toEmojiFlag` will directly return the Unicode emoji for the input country code. For example `"CA"` => 🇨🇦
Use the unicode conversion is working

![image](https://user-images.githubusercontent.com/31044781/184953210-c9418fd5-39cd-4c57-a3ee-a87804808d6b.png)

Will make a pr

**Comment by ckosmic** [comment]
Fixed in https://github.com/ckosmic/ScoreSaberWidget/pull/2
